import Layout from '@/components/Layout';
import { ThemeContext } from '@/store/store';
// import ThemeCtx from '@/store/store';
import Head from 'next/head'
import { useContext } from 'react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Richie Varghese</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1 className="text-2xl font-bold underline dark:text-white">
          {/* Hello world! */}
        </h1>
      </Layout>
    </>
  )
}
